# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/David/Documents/UCSC/CMPE100/Lab7/Lab7.cache/wt [current_project]
set_property parent.project_path C:/Users/David/Documents/UCSC/CMPE100/Lab7/Lab7.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/David/Documents/UCSC/CMPE100/Lab7/Lab7.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/David/Documents/UCSC/CMPE100/Lab7/Lab7.srcs/sources_1/new/mux2_1.v
  C:/Users/David/Documents/UCSC/CMPE100/Lab7/Lab7.srcs/sources_1/new/m4_1e.v
  C:/Users/David/Documents/UCSC/CMPE100/Lab7/Lab7.srcs/sources_1/new/countUD5L.v
  C:/Users/David/Documents/UCSC/CMPE100/Lab7/Lab7.srcs/sources_1/new/rect.v
  C:/Users/David/Documents/UCSC/CMPE100/Lab7/Lab7.srcs/sources_1/new/countUD10L.v
  C:/Users/David/Documents/UCSC/CMPE100/Lab7/Lab7.srcs/sources_1/new/vertBar.v
  C:/Users/David/Documents/UCSC/CMPE100/Lab7/Lab7.srcs/sources_1/new/slug.v
  C:/Users/David/Documents/UCSC/CMPE100/Lab7/Lab7.srcs/sources_1/new/rndNum.v
  C:/Users/David/Documents/UCSC/CMPE100/Lab7/Lab7.srcs/sources_1/new/horBar.v
  C:/Users/David/Documents/UCSC/CMPE100/Lab7/Lab7.srcs/sources_1/new/edgeDect.v
  C:/Users/David/Documents/UCSC/CMPE100/Lab7/Lab7.srcs/sources_1/new/m8_1e.v
  C:/Users/David/Documents/UCSC/CMPE100/Lab7/Lab7.srcs/sources_1/new/m2_1x16.v
  C:/Users/David/Documents/UCSC/CMPE100/Lab7/Lab7.srcs/sources_1/new/count4UDut6.v
  C:/Users/David/Documents/UCSC/CMPE100/Lab7/Lab7.srcs/sources_1/new/count4UDut10.v
  C:/Users/David/Documents/UCSC/CMPE100/Lab7/Lab7.srcs/sources_1/new/VGAcontr.v
  C:/Users/David/Documents/UCSC/CMPE100/Lab7/Lab7.srcs/sources_1/new/Selector.v
  C:/Users/David/Documents/UCSC/CMPE100/Lab7/Lab7.srcs/sources_1/new/RingCNT.v
  C:/Users/David/Documents/UCSC/CMPE100/Lab7/Lab7.srcs/sources_1/new/hex7seg.v
  C:/Users/David/Documents/UCSC/CMPE100/Lab7/Lab7.srcs/sources_1/new/lab7_clks.v
  C:/Users/David/Documents/UCSC/CMPE100/Lab7/Lab7.srcs/sources_1/new/TopMod.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/David/Documents/UCSC/CMPE100/Lab7/Lab7.srcs/constrs_1/new/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/Users/David/Documents/UCSC/CMPE100/Lab7/Lab7.srcs/constrs_1/new/Basys3_Master.xdc]


synth_design -top TopMod -part xc7a35tcpg236-1


write_checkpoint -force -noxdef TopMod.dcp

catch { report_utilization -file TopMod_utilization_synth.rpt -pb TopMod_utilization_synth.pb }
